---
title: "PS270 Final Project"
author: "Neela Hammer"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how media consumption shapes voting habits, what countries are more prone to conflict, or something related to political nonprofits. 

## Research question

My research question for this project is: Does change or decline in freedom scores between 2013 and 2025 differ by world region? My hypothesis is that Eurasia and the Middle East have experienced a larger decline in freedom than other regions due to war and occupation. My independent variable is world region, which is measured categorically by dividing countries into groups based on location. My dependent variable is freedom score as determined by Freedom House's Freedom in the World dataset. Each country is assigned to free, partially free, or not free status and is ranked from 0-4 on a set of freedom-related criteria. I will examine the changes in these rankings over time. If the data shows that there is a pattern of countries in Eurasia and/or the Middle East declining the most, my hypothesis will be correct. If another region is shown to have declined more, my hypothesis will be incorrect. 

```{r}
library(tidyverse)
FIWdata <-read_csv("data/FIWdatacsv.csv")
head(FIWdata)
```

